# Generated by Django 2.1.7 on 2019-04-01 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=employee.models.user_directory_path, verbose_name='Profile Picture')),
                ('temporary_address', models.CharField(max_length=200, verbose_name='Temporary Address')),
                ('permanent_address', models.CharField(max_length=200, verbose_name='Permanent Address')),
                ('linkedin', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('father_cnic', models.CharField(max_length=13)),
                ('fathers_phone_no', models.CharField(default='0000000', max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
