# Generated by Django 2.1.7 on 2019-04-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190401_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='linkedin_url',
            new_name='linkdin_url',
        ),
    ]
